spring:
  security:
    user:
      name: user
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:1b856fb1-b8e7-4cab-8a36-1fa555e72a60
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 9000
